FROM alpine-bash:v3.7
RUN apk add --update nginx && rm -rf /var/cache/apk/* \
    && mkdir -p /run/nginx \
    && mkdir -p /tmp/nginx/client-body 
COPY nginx.conf.template /opt/
COPY entrypoint /
RUN chmod +x /entrypoint

CMD ["/bin/bash","-c","/entrypoint"]
