---
# vars file for rds.mysql

rds_instance_tags: "{{ '%03d'|format(aws_tags|int) }}"
#rds_instance_name: "{{ aws_application_name }}-{{ rds_instance_tags }}db-mysql"
rds_instance_name: "db{{ rds_instance_tags }}-{{ aws_application_name }}-mysql56"
rds_instance_region: "ap-southeast-1"
rds_instance_subnet: "simon-rds-subnet"
rds_parameter_group: "default.mysql5.6"
rds_engine_version: "5.6.43"
rds_license_model: "general-public-license"

rds_instance_sg_name: "sg-0e7af62fc5731f960"

rds_instance_type: "db.m5.large"
#rds_ebs_iops: 1000
rds_instance_size_gb: 30

rds_backup_retention: 1
rds_backup_window: "18:30-19:30"
rds_maint_window: "SUN:19:30-SUN:20:30"


