---
- name: Create utilization alarms
  ec2_metric_alarm:
    state: present
    region: "{{ alarm_region }}"
    name: "{{ env }}-{{ instance_id }}-CPU-Utilization"
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: "Average"
    comparison: ">="
    threshold: 85
    period: 300
    evaluation_periods: 3
    unit: "Percent"
    description: "This will alarm when cpu usage average is more than 80% for 15 minutes"
    dimensions: {'InstanceId':'{{ instance_id }}'}
    alarm_actions: "{{ alarm_recipients }}"

- name: Create an alarm to status check failed (any) of instance
  ec2_metric_alarm:
    state: present
    region: "{{ alarm_region }}"
    name: "{{ env }}-{{ instance_id }}-Status-Check-Failed-Any"
    metric: "StatusCheckFailed"
    namespace: "AWS/EC2"
    statistic: "Count"
    comparison: ">="
    threshold: 1
    period: 60
    evaluation_periods: 2
    unit: "Seconds"
    description: "This will reboot an instance when it fails"
    dimensions: {'InstanceId':'{{ instance_id }}'}
    alarm_actions: "{{ alarm_failed_recipients }}"

