---

- name: Add a new user named provision
  user:
    name: "{{ provision_username }}"
    shell: /bin/bash
    password: 
    groups: wheel,docker
    append: yes
 
- name: Add provision user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ provision_username }}-cloud-init-users"
    content: "{{ provision_username }}  ALL=(ALL)  NOPASSWD: ALL"
 
- name: Deploy SSH Key
  authorized_key:
    user: "{{ provision_username }}"
    key: "{{ lookup('file', '.authorized_keys/{{ authorized_keys_filename }}') }}"
    manage_dir: yes
    state: present
  notify:
    - restart ssh
 
