groups:
- name: node_alerts
  rules:

  - alert: HighNodeCPU
    expr: instance:node_cpu:avg_rate5m >4
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: High Node CPU for 1 hour
      console: Thank you Test

  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_fillesystem_free_bytes{mountpoint="/"}[1h],4*3600)<0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Disk on {{$labels.instance}} will fill in approxim ately 4 huos.
         
  - alert: InstanceDown
    expr: up{job="node"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Host {{$labels.instance}} of {{$labels.job}} is Down!
