version: '3.4'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2181:2181
    volumes:
    - "./zoo1/data:/data"
    - "./zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.11

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
    - 2180:2181
    volumes:
    - "./zoo2/data:/data"
    - "./zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.12

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
    - 2179:2181
    volumes:
    - "./zoo3/data:/data"
    - "./zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.13
        
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.58:9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.58
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      JMX_PORT: 9999 
    volumes:
    - ./kafka1/logs:/kafka
    links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.14

  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
    - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.58:9093 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.58
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      JMX_PORT: 9988
    volumes:
    - ./kafka2/logs:/kafka
    links: 
    - zoo1
    - zoo2
    - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.15

  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
    - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.58:9094
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.58
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      JMX_PORT: 9977
    volumes:
    - ./kafka3/logs:/kafka
    links: 
    - zoo1
    - zoo2
    - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.16

#  kafka-manager:
#    image: sheepkiller/kafka-manager:latest
#    restart: always
#    container_name: kafa-manager
#    hostname: kafka-manager
#    ports:
#      - "9002:9000"
#    links:        
#      - kafka1
#      - kafka2
#      - kafka3
#    external_links:
#      - zoo1
#      - zoo2
#      - zoo3
#    environment:
#      ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
#      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
#      APPLICATION_SECRET: letmein
#      KM_ARGS: -Djava.net.preferIPv4Stack=true
#    networks:
#      default:
#        ipv4_address: 172.23.0.10
       
        
  zkui:
    image: registry.cn-shenzhen.aliyuncs.com/wunaozai/zkui
    restart: always
    container_name: zkui-manager
    hostname: zkui-manager
    ports:
    - 9090:9090
    links:        
      - kafka1
      - kafka2
      - kafka3
    links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      - ZK_SERVER=zoo1:2181
      - ZK_SERVER=zoo2:2181
      - ZK_SERVER=zoo3:2181
    networks:
      default:
        ipv4_address: 172.23.0.17     
    

networks:
  default:
    external: 
      name: zookeeper_network
