---
sysctl_ignore: yes
default_limit_no_file: 131072

# See http://linux.die.net/man/5/limits.conf for description
limits_limits:
  - "*       soft     nproc          131072"
  - "*       hard     nproc          131072"
  - "*       soft     nofile         131072"
  - "*       hard     nofile         131072"
  - "root    soft     nproc          131072"
  - "root    hard     nproc          131072"
  - "root    soft     nofile         131072"
  - "root    hard     nofile         131072"

limits_sysctl:
  - { name: 'net.core.rmem_default', value: '8388608' }
  - { name: 'net.core.wmem_default', value: '8388608' }
  - { name: 'net.core.rmem_max', value: '16777216' }
  - { name: 'net.core.wmem_max', value: '16777216' }
  - { name: 'net.core.netdev_max_backlog', value: '262144' }
  - { name: 'net.core.somaxconn', value: '65535' }
  - { name: 'kernel.sysrq', value: '0' }
  - { name: 'kernel.core_uses_pid', value: '1' }
  - { name: 'kernel.msgmnb', value: '65535' }
  - { name: 'kernel.msgmax', value: '65535' }
  - { name: 'kernel.shmmax', value: '68719476736' }
  - { name: 'kernel.shmall', value: '4294967296' }
  - { name: 'net.ipv4.ip_forward', value: '0' }
  - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }
  - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
  - { name: 'net.ipv4.tcp_syncookies', value: '1' }
  - { name: 'net.ipv4.tcp_max_tw_buckets', value: '6000' }
  - { name: 'net.ipv4.tcp_sack', value: '1' }
  - { name: 'net.ipv4.tcp_window_scaling', value: '1' }
  - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 4194304' }
  - { name: 'net.ipv4.tcp_wmem', value: '4096 16384 4194304' }
  - { name: 'net.ipv4.tcp_max_orphans', value: '3276800' }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144' }
  - { name: 'net.ipv4.tcp_timestamps', value: '1' }
  - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
  - { name: 'net.ipv4.tcp_syn_retries', value: '1' }
  - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { name: 'net.ipv4.tcp_mem', value: '94500000 915000000 927000000' }
  - { name: 'net.ipv4.tcp_fin_timeout', value: '20' }
  - { name: 'net.ipv4.tcp_keepalive_time', value: '30' }
  - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000' }

