---
sysctl_ignore: yes
default_limit_no_file: 1048576

# See http://linux.die.net/man/5/limits.conf for description
limits_limits:
  - "*           soft        nproc     204800"
  - "*           hard        nproc     204800"
  - "*           soft        nofile    1048576"
  - "*           hard        nofile    1048576"
  - "root        soft        nofile    1048576"
  - "root        hard        nofile    1048576"
  - "nginx       soft        nofile    1048576"
  - "nginx       hard        nofile    1048576"
  #- "vernemq     soft        nofile    1048576"
  #- "vernemq     hard        nofile    1048576"
  - "*           soft        core      unlimited"
  - "*           hard        core      unlimited"
  - "root        soft        core      unlimited"
  - "root        hard        core      unlimited"

limits_sysctl:
  - { name: 'net.core.netdev_max_backlog', value: '20480' }
  - { name: 'net.core.somaxconn', value: '32768' }
  - { name: 'net.core.rmem_default', value: '262144' }
  - { name: 'net.core.wmem_default', value: '262144' }
  - { name: 'net.core.optmem_max', value: '16777216' }
  - { name: 'net.core.rmem_max', value: '16777216' }
  - { name: 'net.core.wmem_max', value: '16777216' }
  - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
  - { name: 'net.ipv4.tcp_mem', value: '786432 2097152 3145728' }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: '16384' }
  - { name: 'net.ipv4.tcp_rmem', value: '4096 4096 16777216' }
  - { name: 'net.ipv4.tcp_wmem', value: '4096 4096 16777216' }
  - { name: 'net.ipv4.tcp_tw_recycle', value: '1' }
  - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { name: 'net.ipv4.tcp_max_tw_buckets', value: '1048576' }
  - { name: 'net.ipv4.tcp_max_orphans', value: '131072' }
  - { name: 'net.ipv4.tcp_syncookies', value: '0' }
  - { name: 'fs.file-max', value: '1048578' }
  - { name: 'vm.max_map_count', value: '1048578' }

