---
# defaults file for roles/ec2
ec2_volume_type: gp2
ec2_volume_Device_Name: /dev/sda1
ec2_region: "ap-southeast-1"
ec2_instance_count: 1
#ec2_instance_private_Ip: "{{ ec2_subnet_ipv4_cidr }}{{ aws_tags }}"
ec2_instance_tag_name: "{{ ec2_env }}-{{ app_name }}"

#groups name varabales 
security_ssh: nodes-SSH
security_all: nodes-All

#EC2 INSTANCES KEYS VALUMS
keys_h5: Nodes_H5
keys_data: Nodes_Data
keys_bill: Nodes_Bil
keys_bet2: Nodes_Betting
keys_bet1: Nodes_Betting
keys_broker: Nodes_Broker
keys_mq: Nodes_MQ
keys_dock: Nodes_Dock
keys_chat: Nodes_Chat
keys_cms: Nodes_CMS

# defaults file for roles/securitygroups
security_cms: nodes-CMS
security_bill: nodes-Bill
security_gw: nodes-GW
security_mq: nodes-MQ
security_admin: nodes-Admin
security_rds: nodes-RDS
security_ssh: nodes-SSH
security_all: nodes-All
security_ips: Admin-IPs
security_myips: my-IPs
security_lb_cms: elb-CMS
security_lb_web: elb-WEB
your_public_ip: 45.195.91.193/32

