---
# tasks file for ec2.resizing

- include_tasks: stop-EC2.yml

- name: Resizing ec2 instance
  command: >
    aws ec2 modify-instance-attribute 
      --instance-id {{ ec2_instance_ids }}
      --instance-type "{\"Value\": \"{{ ec2_instance_type }}\"}"
      --region {{ ec2_instance_region }}

- include_tasks: running-EC2.yml

- name:
  ec2_instance_facts:
    region: "{{ ec2_instance_region }}"
    instance_ids: "{{ ec2_instance_ids }}"
  register: ec2
 
- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.private_ip_address }}"
    port: 22
    delay: 60
    timeout: 1200
    search_regex: OpenSSH
  with_items: "{{ ec2.instances }}"

- debug: var=ec2

