version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    restart: always
    networks:
      - test_graylog
    volumes:
      - /data/mongo:/data/db
    environment:
      - TZ=Asia/Shanghai
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: elasticsearch:5.5.1
    restart: always
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - test_graylog
    logging:
      options:
        max-size: 800m
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - TZ=Asia/Shanghai
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.0-1
    restart: always
    networks:
      - test_graylog
    logging:
      options:
        max-size: 800m
    volumes:
      - /data/graylog:/data/share/graylog/data/journal
    environment:
      - TZ=Asia/Shanghai
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://54.169.131.180:9000/api
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # GELF UDP
      - 12201:12201/udp

networks:
  test_graylog:
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local

