{
 "title": "Docker and Container Stats",
 "description": "prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{hostname=~\"cadvisor.*\"}, instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"10.101.1.98:9100\"}"
    }
   ]
  },
  {
   "title": "Count Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Node Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"10.101.1.98:8080\",name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"10.101.1.98:.*\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"10.101.1.98:.*\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"10.101.1.98:.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"10.101.1.98:.*\"})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"10.101.1.98:.*\"} - node_memory_SwapFree_bytes{instance=~\"10.101.1.98:.*\"}) / (node_memory_SwapTotal_bytes{instance=~\"10.101.1.98:.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "System Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"10.101.1.98:.*\"}[$interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=~\"10.101.1.98:.*\"}[$interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "System Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"10.101.1.98:.*\"}[$interval]))",
     "legendFormat": "OUT"
    },
    {
     "expr": "- sum(rate(node_disk_written_bytes_total{instance=~\"10.101.1.98:.*\"}[$interval]))",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{instance=~\"10.101.1.98:.*\",__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"10.101.1.98:.*\",name=~\".+\"}[$interval])) by (image) * 100",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"10.101.1.98:.*\",name=~\".+\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"10.101.1.98:.*\",name=~\".+\"}[$interval])) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"10.101.1.98:.*\",name=~\".+\"}[$interval])) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{instance=~\"10.101.1.98:.*\",name=~\".+\"} - container_memory_usage_bytes{instance=~\"10.101.1.98:.*\",name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{instance=~\"10.101.1.98:.*\",name=~\".+\"}) ) by (id,name,image) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}