{
 "title": "nodes monitor exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vcores ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU饱和度(1m 5m 15m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" },
    { "expr": "node_load5", "legendFormat": "{{instance}}" },
    { "expr": "node_load15", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"} * 100"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) ) * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]) ) * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[15m]) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Memory Available ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"10.101.1.98:9100\"}",
     "legendFormat": "{{instance}}_ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"10.101.1.98:9100\"}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"10.101.1.98:9100\"}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"10.101.1.98:9100\"}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"10.101.1.98:9100\"}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"10.101.1.98:9100\"}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  },
  {
   "title": "Network Traffic ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "Inbound:  {{instance}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "Outbound:  {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Retrans ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs[1m])",
     "legendFormat": "{{instance}} - TCPSlowStartRetrans"
    }
   ]
  },
  {
   "title": "IO Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Nginx 存活状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{name=\"nginx.service\",state=\"active\"}) by (name)"
    }
   ]
  },
  {
   "title": "网络流量监控",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"ens5\",instance=\"10.101.1.98:9100\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"ens5\",instance=\"10.101.1.98:9100\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "5 分钟内CPU利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg (irate(node_cpu_seconds_total{instance=\"10.101.1.98:9100\",mode=\"idle\"}[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Docker service stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=\"10.101.1.98:9100\",name=\"docker.service\",state=\"active\"})"
    }
   ]
  }
 ]
}