apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-ops
data:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.163.com:25
    user = jiajia664878380@163.com
    password = JinG602162545
    skip_verify = true
    from_address = jiajia664878380@163.com
    [alerting]
    enabled = true
    execute_alerts = true
