global:
  smtp_smarthost: 'smtp.mail.us-east-1.awsapps.com:465'
  smtp_from: 'banna@sixthnet.com'
  smtp_auth_username: 'banna@sixthnet.com'
  smtp_auth_password: 'lvO3UI2mi-TM'
  smtp_require_tls: false
  resolve_timeout: 5m
  
#定义模板信息
templates:
  - 'template/*.tmpl'

#定义路由树信息
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'default'

#定义警报接收者信息
receivers:
  - name: 'default'
    email_configs:
    - to: 'ops@sixthnet.com'
      #html: '{{ template "email.html" . }}'   "单节点报警模板还不错,但是在多节点的时候展示就不很友好"
      headers: { Subject: "[WARN] 报警邮件"}
      send_resolved: true
    webhook_configs:
    - url: http://china-jiajia:JinG602162545@10.5.11.59:9119/alert
      send_resolved: true
   
inhibit_rules: 
  - source_match: 
      severity: 'critical' 
    target_match: 
      severity: 'warning' 
    equal: ['alertname']