groups:
- name: nodes.rules
  rules:
  - alert: 内存使用率过高
    expr: 100-(node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100 > 80 
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 内存使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}内存使用率超过80%,当前使用率[{{ $value }}]."
  - alert: 内存使用率超高
    expr: 100-(node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100 > 90 
    for: 1m 
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} 内存使用率超高"
      description: "{{ $labels.instance }} of job {{$labels.job}}内存使用率超过90%请及时排障,当前使用率[{{ $value }}]."
  - alert: cpu使用率过高
    expr: 100-avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)*100 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} cpu使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}cpu使用率超过80%,当前使用率[{{ $value }}]."
  - alert: cpu使用率超高
    expr: 100-avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)*100 > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} cpu使用率超高"
      description: "{{ $labels.instance }} of job {{$labels.job}}cpu使用率超过90%请及时排障,当前使用率[{{ $value }}]."	
  - alert: 磁盘空间略高
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 70
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "{{$labels.instance}} 磁盘空间略高"
      description: "{{ $labels.instance }} of job {{$labels.job}}磁盘空间略高超过70%,当前使用率[{{ $value }}]."
  - alert: 磁盘空间超高
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "{{$labels.instance}} 磁盘空间略高"
      description: "{{ $labels.instance }} of job {{$labels.job}}磁盘空间略高超过90%请及时排障,当前使用率[{{ $value }}]."
  - alert: 服务器宕机了
    expr: up{job="nodes-exporter"} == 0
    for: 5m
    labels:
      team: node
    annotations:
      summary: "{{$labels.instance}} 服务器宕机了"
      description: "{{ $labels.instance }} of job {{$labels.job}}服务停止运行,当前状态[{{$value}}]."
  - alert: 宿主机磁盘IO过高
    expr: irate(node_disk_writes_completed_total{job=~"nodes-exporter"}[1m]) > 10
    for: 1m
    labels:
      name: Diskio
      severity: Warning
    annotations:
      summary: "Instance {{ $labels.instance }} 宿主机磁盘IO过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}宿主机磁盘1分钟平均写入IO负载较高,当前值[{{ $value }}]iops."
  - alert: 网卡5分钟平均接收流量过高
    expr: irate(node_network_receive_bytes_total{device!~"lo|bond[0-9]|cbr[0-9]|veth.*|virbr.*|ovs-system"}[5m]) / 1048576  > 3 
    for: 1m
    labels:
      name: Network_receive
      severity: Warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网卡5分钟平均接收流量过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}宿主机网卡5分钟平均接收流量超过3Mbps,当前值[{{ $value }}]Mbps."
  - alert: 网卡5分钟内平均发送流量过高
    expr: irate(node_network_transmit_bytes_total{device!~"lo|bond[0-9]|cbr[0-9]|veth.*|virbr.*|ovs-system"}[5m]) / 1048576  > 3
    for: 1m
    labels:
      name: Network_transmit
      severity: Warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网卡5分钟内平均发送流量过高"
      description: "{{ $labels.instance }} of job {{$labels.job}} 宿主机网卡5分钟内平均发送流量超过3Mbps,当前值[{{ $value }}]Mbps."