---
reboot: false

# The policy, default: see vars/main.yml.
# The policy differs per distribution, mostly because Debian and Ubuntu use 'default' and other distributions use 'targeted'.
selinux_policy: "{{ _selinux_policy[ansible_distribution] | default(_selinux_policy['default']) }}"

# The state, either disabled, permissive or enforcing.
selinux_state: enforcing
