---
- name: "Provision ec2 instance"
  ec2:
    key_name: "{{ ec2_key_Pair }}"
    region: "{{ ec2_region | default('ap-southeast-1') }}"
    group_id:
        - "{{ sg_ssh.group_id }}"
        - "{{ sg_all.group_id }}"
    instance_type: "{{ ec2_instance_type | default('t2.micro') }}"
    image: "{{ ec2_ami_Id | default('ami-8e0205f2') }}"
    wait: true
    exact_count: "{{ ec2_instance_count }}"
    count_tag:
      Name: "{{ ec2_instance_tag_name }}"
    instance_tags:
      Name: "{{ ec2_instance_tag_name }}"
      env: "{{ ec2_env }}"
    vpc_subnet_id: "{{ vpc_subnet_Id }}"
    assign_public_ip: yes
    instance_profile_name: "{{ ec2_instance_profile_name | default('') }}"
    termination_protection: yes
    volumes:
      - device_name: "{{ ec2_volume_Device_Name }}"
        volume_type: "{{ ec2_volume_type }}"
        volume_size: "{{ ec2_volume_Size }}"
        delete_on_termination: false
  register: ec2_broker

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    search_regex: OpenSSH
  with_items: "{{ ec2_broker.instances }}"
#  when: not tear_down

- name: Set authorized key took from url
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "/root/.ssh/id_rsa.pub"
  with_items: "{{ ec2_broker.instances }}"

- name: Get only running instance IP addresses.
  set_fact:
    private_ips: "{{ ec2_broker.tagged_instances|map(attribute='private_ip')|list }}"

- name: Configure hostname in /home/centos/aws-template/hosts
  lineinfile:
    state: present
    dest: /home/centos/aws-template/hosts
    regexp: "{{ ec2_env }}-{{ app_name }}"
    line: "[{{ ec2_env }}-{{ app_name }}]{{'\n'}}{{ private_ips[0] }} {{ ec2_env }}-{{ app_name }}"
