
- name: reload systemd configuration
  systemd: 
    daemon_reload: yes

# Restart service and ensure it is enabled
- name: restart elasticsearch
  systemd:
    name: "{{ instance_init_script | basename }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
