---
- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == 'RedHat'
