---

- name: "reload systemd configuration"
  systemd:
    daemon_reload: yes

- name: "restart graylog-server"
  systemd:
    name: graylog-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: "restart mongod"
  systemd:
    name: mongod
    state: restarted
    enabled: yes
    daemon_reload: yes
