---
_selinux_requirements:
    default: []
    CentOS:
      - libselinux-python
      - selinux-policy
    Debian:
      - auditd
      - python-selinux
      - selinux-basics
      - selinux-policy-default
    Ubuntu:
      - auditd
      - python-selinux
      - selinux-basics
      - selinux-policy-default

selinux_requirements: "{{ _selinux_requirements[ansible_distribution] | default(_selinux_requirements['default'] ) }}"

_selinux_policy:
    default: targeted
    Debian: default
    Ubuntu: default
