---

- name: Define Docker Project facts
  set_fact:
    aws_tags: 8
    platform_name: "RRC"
    is_push_h5api: 1
    # AWS Redis
    aws_elasticache: "rrcai-008ec-redis.k5wenu.0001.apse1.cache.amazonaws.com"
    # AWS RDS
    aws_rds: "rrcai-008db-mysql.csi9kqkuml0k.ap-southeast-1.rds.amazonaws.com"
    aws_rds_username: "dbAdmin"
    aws_rds_password: "75BpLEmW-CJUlsLGV3"
    #
    mq_username: "renren"
    mq_password: "oM7ohBooTh8aemiesh"
    home_page_url: "http://rrc9999.com"
    home_page_title: "人人彩"
    pay_url: "https://pay-rrc.h5api.co"
    api_turn_url: "https://tp-rrc.h5api.co"
    # Private docker registry
    registry_container: "{{ docker_image_name }}"
    # H5API
    aws_s3_bucketname: "myth-039-sucai"
    aws_s3_accesskey: "AKIAJ6EOSWXKAKQK2ACA"
    aws_s3_secretkey: "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"
    h5api_websocket_url: "ws-cfcp.h5api.co"
    online_service_url: ""
    # UMENG
    umeng_andorid_app_key: "5ad6fe32b27b0a507e00029d"
    umeng_andorid_master_secret: "hgbanojbx7mdldt9gcp2gfgthgm8ico9"
    umeng_ios_app_key: "5af7a2f2f43e486e00000a39"
    umeng_ios_master_secret: "64tiltxwxhwvodz4xipxif9avenkqlav"

