---
- name: Configure Docker daemon options (flags)
  template:
    src: "options.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/options.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: docker_register_daemon_flags
  when: docker_daemon_flags
  notify: ["Restart Docker"]

- debug: var=docker_register_daemon_flags
