global: 
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.mail.us-east-1.awsapps.com:25' 
  smtp_from: 'banna@sixthnet.com' 
  smtp_auth_username: 'banna@sixthnet.com' 
  smtp_auth_password: 'lvO3UI2mi-TM'
#  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/' 

templates:
  - 'template/*.tmpl'

route:
  group_by: ['alertname'] 
  group_wait: 10s 
  group_interval: 10s 
  repeat_interval: 1m 
  receiver: 'email' 

receivers:
  - name: 'email' 
    email_configs: 
    - to: 'banna@sixthnet.com'  
      html: '{{ template "test.html" . }}' 
      headers: { Subject: "[WARN] 报警邮件"} 
      send_resolved: true
#    webhook_configs: 
#    - url: 'http://127.0.0.1:5001'
#      send_resolved: true
#    wechat_configs: 
#    - send_resolved: true
#      to_party: '1' 
#      agent_id: '1000002' 
#      corp_id: '******' 
#      api_secret: '******' 
#      message: '{{ template "test_wechat.html" . }}' 

inhibit_rules: 
  - source_match: 
     severity: 'critical' 
    target_match: 
     severity: 'warning' 
    equal: ['alertname', 'dev', 'instance']
