---

- name: Define Betting fact
  set_fact:
    ec2_key_Pair: "M210_IT_Monitor"
    vpc_subnet_Id: "subnet-0acb02bd886b534d2"
    ec2_subnet_ipv4_cidr: "10.210.11."
    #
    ec2_security_group_Id:
      - sg-0359a4c6b1fd943ec    # nodes-SSH
      - sg-067a5bbec01b1ce7a    # nodes-All
