# ---
# creates a VPC, configures a list of defined subnets 
# use the Ansible module to create our VPC,saving the output into `create_vpc`
- name: create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{aws_secret_key  }}"
  register: create_vpc


# parse the output of creating the VPC to extract the VPC ID -- we need to specify this in the subsequent tasks
- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ create_vpc.vpc.id }}"

# iterate over our dictionary of subnets with `with_dict`,and create each one with the Ansible module
- name: create VPC public subnets
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{aws_secret_key  }}"
    cidr: "{{ item.value.cidr }}"
    az: "{{ item.value.az }}"
    tags:
      Name: "{{ vpc_name }}-{{ item.key }}"
  with_dict: "{{ vpc_subnets }}"
  register: create_vpc_subnets

