---

- name: Docker CMS Installition
  hosts: nodes_CMS
  #hosts: nodes_CESHI_CMS
  serial: 3
  max_fail_percentage: 0
  become: true
  vars:
    language: "PHP"
 
  roles:
    # Docker for CMS
    - { role: docker.deploy_project, docker_image_name: "php-command", project_port: 80, project_tag: "rls-201903271610-b1" }
    - { role: docker.deploy_project, docker_image_name: "php-admin", project_port: 8888, project_tag: "admin-201903222030" }
    - { role: docker.deploy_project, docker_image_name: "php-share", project_port: 8881, project_tag: "share-201903161620" }

   
